name: Ejecutar Script de Asistencia Diaria

on:
  schedule:
    # Ejecutar a las 5:00 AM hora de Perú (UTC-5) de lunes a viernes
    # En GitHub Actions se usa UTC, por lo que 5:00 AM en Perú es 10:00 AM UTC
    - cron: "0 10 * * 1-5"

  # Permite la ejecución manual para pruebas
  workflow_dispatch:

jobs:
  ejecutar-script-asistencia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar TypeScript
        run: npx tsc

      - name: Ejecutar script de asistencia diaria
        run: node ./dist/jobs/asistencia/SetDatosAsistenciaDiaria.js
        env:
          DATABASE_URL: ${{ secrets.RDP02_INS1_DATABASE_URL }}
          BLOB_READ_WRITE_TOKEN: ${{ secrets.VERCEL_BLOB_INS1_READ_WRITE_TOKEN }}
